#!/bin/bash

# AirGit Setup Script
# This script helps you set up AirGit with the correct SSH configuration

set -e

echo "🚀 AirGit Setup"
echo "==============="
echo ""

# Read configuration
read -p "SSH Host [localhost]: " SSH_HOST
SSH_HOST=${SSH_HOST:-localhost}

read -p "SSH Port [22]: " SSH_PORT
SSH_PORT=${SSH_PORT:-22}

read -p "SSH User [git]: " SSH_USER
SSH_USER=${SSH_USER:-git}

read -p "SSH Key Path [~/.ssh/id_rsa]: " SSH_KEY
SSH_KEY=${SSH_KEY:-$HOME/.ssh/id_rsa}

read -p "Remote Repository Path (absolute): " REPO_PATH

read -p "Listen Address [0.0.0.0]: " LISTEN_ADDR
LISTEN_ADDR=${LISTEN_ADDR:-0.0.0.0}

read -p "Listen Port [8080]: " LISTEN_PORT
LISTEN_PORT=${LISTEN_PORT:-8080}

# Expand tilde in paths
SSH_KEY="${SSH_KEY/#\~/$HOME}"

# Test SSH connection
echo ""
echo "Testing SSH connection..."
if ssh -i "$SSH_KEY" -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "cd $REPO_PATH && git status" > /dev/null 2>&1; then
    echo "✓ SSH connection successful"
else
    echo "✗ SSH connection failed. Please check your credentials."
    exit 1
fi

# Create .env file
cat > .env << EOF
# AirGit Configuration (generated by setup.sh)

AIRGIT_SSH_HOST=$SSH_HOST
AIRGIT_SSH_PORT=$SSH_PORT
AIRGIT_SSH_USER=$SSH_USER
AIRGIT_SSH_KEY=$SSH_KEY

AIRGIT_REPO_PATH=$REPO_PATH

AIRGIT_LISTEN_ADDR=$LISTEN_ADDR
AIRGIT_LISTEN_PORT=$LISTEN_PORT
EOF

echo ""
echo "✓ Configuration saved to .env"
echo ""
echo "Next steps:"
echo "1. Build: make build"
echo "2. Run:   ./airgit"
echo "3. Visit: http://$LISTEN_ADDR:$LISTEN_PORT"
